package wsp

import (
	"errors"
	"fmt"
	"io/fs"
	"maps"
	"os"
	"path/filepath"
	"slices"
	"strings"

	"github.com/Phaengris/claude-workspaces/internal/alloc"
	"github.com/Phaengris/claude-workspaces/internal/config"
)

const (
	workspaceMDName = "WORKSPACE.md"
	claudeMDName    = "CLAUDE.md"
	envFileName     = ".env"
)

// claudeMDBody is the entire generated CLAUDE.md: one line pointing at the
// generated file. Everything a workspace knows about itself lives in
// WORKSPACE.md, which is regenerated wholesale; CLAUDE.md is written once and
// then belongs to the agent, so anything the tool wants to say later has to be
// said through the reference, never by editing this file (spec §5).
const claudeMDBody = "See @WORKSPACE.md for this workspace's task, projects, values, and per-project instructions.\n"

// WriteWorkspaceMD regenerates <ws.Dir>/WORKSPACE.md from scratch. Every fact
// in it is derived at call time — the allocation, alloc.ComputeValues, and
// ProjectStates (only projects actually checked out here) — so the file is a
// projection of reality rather than a second source of truth, and a stale
// section from an earlier generation cannot survive a rewrite.
//
// The layout is this function's own; it is pinned byte-for-byte by
// testdata/workspace_md.golden. Guarantees the golden must keep: the workspace
// name, task id and description appear; each checked-out project gets a
// section with `dir:` and `branch:` lines followed by its configured
// instructions verbatim; values appear as sorted NAME0=… lines; a project with
// at least one daemon gets a Services block, in start order, naming the
// workspace itself in the `workspace up`/`logs` examples and appending
// ` — ` + the runtime-substituted description only when one is configured; a
// project with no daemons gets no Services block at all.
//
// Project dirs are written relative to the workspace dir: the reader (an agent
// working in ws.Dir) can use them as-is, and the file stays identical no
// matter where the workspace root lives. A work tree whose branch cannot be
// read renders as "(unknown)" rather than an empty line — see ProjectStates on
// why an unreadable branch is not an error.
func WriteWorkspaceMD(cfg *config.Config, ws Workspace) error {
	var b strings.Builder

	fmt.Fprintf(&b, "# %s\n\n", ws.Name())
	fmt.Fprintf(&b, "- task: %s\n", ws.Alloc.TaskID)
	fmt.Fprintf(&b, "- description: %s\n", ws.Alloc.Description)
	if ws.Alloc.CreatedAt != "" {
		fmt.Fprintf(&b, "- created: %s\n", ws.Alloc.CreatedAt)
	}
	b.WriteString("\nGenerated by `workspace` and rewritten on every new/checkout — " +
		"keep durable notes in CLAUDE.md instead.\n")

	b.WriteString("\n## Values\n\n")
	values := alloc.ComputeValues(cfg.Values, ws.Alloc.Index)
	if len(values) == 0 {
		b.WriteString("(none)\n")
	} else {
		b.WriteString("```\n")
		for _, k := range slices.Sorted(maps.Keys(values)) {
			fmt.Fprintf(&b, "%s=%s\n", k, values[k])
		}
		b.WriteString("```\n")
	}

	b.WriteString("\n## Projects\n")
	states := ProjectStates(cfg, ws)
	if len(states) == 0 {
		b.WriteString("\n(none checked out)\n")
	}
	for _, st := range states {
		rel, err := filepath.Rel(ws.Dir, st.Dir)
		if err != nil {
			rel = st.Dir
		}
		branch := st.Branch
		if branch == "" {
			branch = "(unknown)"
		}
		fmt.Fprintf(&b, "\n### %s\n\n", st.Name)
		fmt.Fprintf(&b, "- dir: %s\n", rel)
		fmt.Fprintf(&b, "- branch: %s\n", branch)
		if p := cfg.Projects[st.Name]; p != nil && strings.TrimSpace(p.Instructions) != "" {
			// Verbatim, with exactly one trailing newline so the next
			// section starts cleanly regardless of how the YAML scalar
			// ended.
			fmt.Fprintf(&b, "\n%s\n", strings.TrimRight(p.Instructions, "\n"))
		}
		if ds := DaemonsOf(cfg, st.Name); len(ds) > 0 {
			vars := RuntimeVars(cfg, ws.Alloc.TaskID, st.Name, ws.Alloc.Index)
			fmt.Fprintf(&b, "\nServices — not started automatically; start what you need with\n"+
				"`workspace up %s <daemon>` and follow it with\n"+
				"`workspace logs %s <daemon>`:\n\n", ws.Name(), ws.Name())
			for _, d := range ds {
				if d.Description == "" {
					fmt.Fprintf(&b, "- %s\n", d.Name)
					continue
				}
				fmt.Fprintf(&b, "- %s — %s\n", d.Name, Subst(d.Description, vars))
			}
		}
	}

	path := filepath.Join(ws.Dir, workspaceMDName)
	if err := os.WriteFile(path, []byte(b.String()), 0o644); err != nil {
		return fmt.Errorf("writing %s: %w", path, err)
	}
	return nil
}

// EnsureClaudeMD creates <ws.Dir>/CLAUDE.md with a one-line reference to
// WORKSPACE.md if and only if no CLAUDE.md is there. An existing file is left
// byte-for-byte alone, whatever it contains — that is the spec §5 promise that
// agent notes survive regeneration (v1 lost them). The O_EXCL create is what
// makes the check-and-write atomic, so two concurrent commands cannot race one
// into clobbering the other's notes.
func EnsureClaudeMD(ws Workspace) error {
	path := filepath.Join(ws.Dir, claudeMDName)
	f, err := os.OpenFile(path, os.O_WRONLY|os.O_CREATE|os.O_EXCL, 0o644)
	if errors.Is(err, fs.ErrExist) {
		return nil
	}
	if err != nil {
		return fmt.Errorf("creating %s: %w", path, err)
	}
	if _, err := f.WriteString(claudeMDBody); err != nil {
		f.Close()
		return fmt.Errorf("writing %s: %w", path, err)
	}
	if err := f.Close(); err != nil {
		return fmt.Errorf("writing %s: %w", path, err)
	}
	return nil
}

// WriteEnvFile writes <ProjectDir>/.env for one project: the source repo's own
// .env as defaults, with the workspace's ResolvedEnv overlaid on top (the
// workspace always wins — its values carry the allocated ports and the
// per-workspace database names). Output is sorted K=V lines with a trailing
// newline, mode 0600.
//
// A missing source .env is normal, not an error: the result is then the
// overlay alone. The destination directory must already exist — it is the
// project's work tree, created by the caller's worktree step.
//
// The mode is forced with an explicit chmod because O_CREATE only applies the
// permission bits when the file did not exist; a .env inherited at 0644 from
// an earlier tool or a hand copy gets tightened rather than left readable.
func WriteEnvFile(cfg *config.Config, ws Workspace, project string) error {
	merged := map[string]string{}
	if p := cfg.Projects[project]; p != nil && p.Repo != "" {
		src := filepath.Join(p.Repo, envFileName)
		data, err := os.ReadFile(src)
		switch {
		case errors.Is(err, fs.ErrNotExist):
			// No defaults to seed from; the overlay stands alone.
		case err != nil:
			return fmt.Errorf("reading %s: %w", src, err)
		default:
			merged = parseEnvFile(string(data))
		}
	}
	maps.Copy(merged, ResolvedEnv(cfg, ws.Alloc.TaskID, project, ws.Alloc.Index))

	var b strings.Builder
	for _, k := range slices.Sorted(maps.Keys(merged)) {
		fmt.Fprintf(&b, "%s=%s\n", k, merged[k])
	}

	dest := filepath.Join(ProjectDir(ws, cfg, project), envFileName)
	if err := os.WriteFile(dest, []byte(b.String()), 0o600); err != nil {
		return fmt.Errorf("writing %s: %w", dest, err)
	}
	if err := os.Chmod(dest, 0o600); err != nil {
		return fmt.Errorf("securing %s: %w", dest, err)
	}
	return nil
}

// parseEnvFile reads dotenv-style defaults: one KEY=VALUE per line, key
// trimmed, value taken verbatim after the first "=" — quotes, spaces and all,
// because these lines are defaults to be re-emitted, not shell to be
// evaluated. Blank lines and lines whose first non-space character is "#" are
// skipped. A line with no "=", or with an empty key, is malformed and is
// skipped too: seeding is best-effort convenience, and failing a checkout over
// a stray line in someone's repo would be worse than ignoring it. On a
// repeated key the last occurrence wins, matching how a shell sourcing the
// file would end up.
func parseEnvFile(data string) map[string]string {
	out := map[string]string{}
	for _, line := range strings.Split(data, "\n") {
		line = strings.TrimSuffix(line, "\r") // tolerate CRLF files
		trimmed := strings.TrimSpace(line)
		if trimmed == "" || strings.HasPrefix(trimmed, "#") {
			continue
		}
		k, v, ok := strings.Cut(line, "=")
		k = strings.TrimSpace(k)
		if !ok || k == "" {
			continue
		}
		out[k] = v
	}
	return out
}
